# Generated by Django 3.1.2 on 2020-12-02 01:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 1, 20, 43, 46, 760398))),
                ('order_finished', models.BooleanField(default=False)),
                ('order_total', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 1, 20, 43, 46, 800322))),
                ('menu_name', models.CharField(default='', max_length=200)),
                ('changed_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=200)),
                ('item_quantity', models.IntegerField(default=1)),
                ('item_price', models.FloatField(default=1.0)),
                ('on_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OrderingSystem.itemcategory')),
                ('on_menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OrderingSystem.itemmenu')),
                ('on_order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OrderingSystem.order')),
            ],
        ),
    ]
