# Generated by Django 3.1.2 on 2020-12-02 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingSystem', '0002_auto_20201201_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='last_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 7, 39, 27, 261401)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 7, 39, 27, 220181)),
        ),
    ]
