# Generated by Django 3.1.2 on 2020-12-02 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingSystem', '0007_auto_20201202_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='last_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 18, 56, 13, 310139)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 18, 56, 13, 271266)),
        ),
    ]
