# Generated by Django 3.1.2 on 2020-12-03 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingSystem', '0009_auto_20201202_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='last_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 19, 6, 37, 284326)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 19, 6, 37, 246255)),
        ),
    ]
