# Generated by Django 3.1.4 on 2020-12-03 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingSystem', '0011_auto_20201202_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='last_changed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 16, 21, 24, 417963)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 16, 21, 24, 382210)),
        ),
    ]
